finalarm_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Trajectory Controllers----------------------------------------
finalarm_joint_trajectory_action_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

# Position Controllers ----------------------------------------
finalarm_position_controller_8:
  type: position_controllers/JointPositionController
  joint: joint_8
  pid: {p: 500, i: 0.01, d: 0.0}

finalarm_position_controller_9:
  type: position_controllers/JointPositionController
  joint: joint_9
  pid: {p: 500, i: 0.01, d: 0.0}

